### ISSUE TITLE
DESIGN

### ISSUE THREAD

**Issue by Lakshyaraj-Singh** [GDG-On-Campus-ICTU/MaterialHub-Hactoberfest#10]
Hi,
I have changed the css :
1) Added new BG color
2) Change the color of tags

please assign me this issue under hactoberfest badge , So ican send the PR.
Thankyou

**Comment by Lakshyaraj-Singh** [comment]
can you assign this to me? @Nde-Dilan  @Apache-ghost

**Comment by Nde-Dilan** [comment]
Can you provide more description on what you have done, like the end result? Some screenshot will be good!

**Comment by Lakshyaraj-Singh** [comment]
sure

**Comment by Lakshyaraj-Singh** [comment]
![Screenshot (195)](https://github.com/user-attachments/assets/ca697876-ec38-484f-a6d5-a673164d69c6)
![Screenshot (195)](https://github.com/user-attachments/assets/507d7341-5a05-4937-9608-a0e439d7c51f)

**Comment by Lakshyaraj-Singh** [comment]
![Screenshot (194)](https://github.com/user-attachments/assets/f0f332c9-790a-4fab-b4e4-5310ebf1b223)

**Comment by Lakshyaraj-Singh** [comment]
![Screenshot (194)](https://github.com/user-attachments/assets/53f44073-3994-4cec-a77f-6966fe084d6c)
can I send the PR ,if you assign the issue @Nde-Dilan 
thankyou

**Comment by Lakshyaraj-Singh** [comment]
@Apache-ghost?

**Comment by Nde-Dilan** [comment]
Hello, sorry for the delay. It was already night here when you were writing.

Consider not to change what other contributors have done, but instead add something new.

Check out the list of open issues to find something!

Cheers and Happy Hacking!
