### ISSUE TITLE
New feature: dark mode.

### ISSUE THREAD

**Issue by gurshaan17** [GDG-On-Campus-ICTU/MaterialHub-Hactoberfest#6]

**Comment by gurshaan17** [comment]
> _No description provided._

The user should be able to toggle between dark and light mode

**Comment by gurshaan17** [comment]
can you assign this to me @Nde-Dilan

**Comment by Apache-ghost** [comment]
## okay , we are waiting for your pull request
### The instructions are in the Readme.md file

**Comment by gurshaan17** [comment]
> ## okay , we are waiting for your pull request
> ### The instructions are in the Readme.md file

<img width="1301" alt="Screenshot 2024-10-10 at 7 00 00 PM" src="https://github.com/user-attachments/assets/53e2eabd-c299-41bb-b8bb-ed7bff51a764">

Should I send PR?
